# docker-compose.yml

services:
  # SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: diviora-db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Test123!'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - db_data:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Test123!' -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Your NestJS Application
  api:
    build: .
    container_name: diviora-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
